apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - name: jupyter-notebook
          image: {{ .Values.jupyter.image }}:{{ .Values.jupyter.tag }}
          ports:
            - containerPort: 8888
          env:
            - name: JUPYTER_TOKEN
              value: "nhatnam123" # Replace with your desired password
