apiVersion: v1
kind: Service
metadata:
  name: dremio
spec:
  selector:
    app: dremio
  ports:
    - protocol: TCP
      port: 9047
      targetPort: 9047
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  type: LoadBalancer
  selector:
    app: jupyter-notebook
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

