minio:
  image: minio/minio
  tag: latest
  storage: 10Gi

dremio:
  image: dremio/dremio-oss
  tag: latest
  storage: 20Gi

jupyter:
  image: jupyter/base-notebook
  tag: latest

ingress:
  enabled: true
  host: 35.198.198.21.nip.io
  tls:
    enabled: true
    secretName: tls-secret